### ISSUE TITLE
Bottom part of STM32 nucleo blocks downstream0 port

### ISSUE THREAD

**Issue by occheung** [sinara-hw/Humpback#11]
![20200702_102821](https://user-images.githubusercontent.com/54844539/86310218-11303900-bc50-11ea-839a-b5c808185c57.jpg)
![20200702_102834](https://user-images.githubusercontent.com/54844539/86310221-13929300-bc50-11ea-8d90-8f6cfd21962e.jpg)
![20200702_102846](https://user-images.githubusercontent.com/54844539/86310226-155c5680-bc50-11ea-9c99-365299a34e1d.jpg)

**Comment by gkasprow** [comment]
Just solder correct stacking height connectors! This boards was not supposed to be plugged directy.

**Comment by sbourdeauducq** [comment]
Do you have part numbers for suitable connectors? With "regular" ~1cm ones, the Nucleo board can be mounted but the EEM connector is obstructed.
BTW this is less of a problem for Nucleo h743zi (as opposed to h743zi2) since the JTAG module can be detached on h743zi.

**Comment by gkasprow** [comment]
I'm using elevated connectors for boards plugged to RPI: BSSH-113-D-10-G or ESW-113-23-S-D

**Comment by gkasprow** [comment]
they mate with standard female 2.54 sockets

**Comment by sbourdeauducq** [comment]
Ordering:
* 16 pins: Mouser No:200-ESW10823GD; Mfr. No: ESW-108-23-G-D
* 20 pins: Mouser No:200-ESW11023GD; Mfr. No: ESW-110-23-G-D
* 30 pins: Mouser No:200-ESW11523GD; Mfr. No: ESW-115-23-G-D
* 34 pins: Mouser No:200-ESW11723GD; Mfr. No: ESW-117-23-G-D

**Comment by sbourdeauducq** [comment]
OK, this works. Please close

**Comment by gkasprow** [comment]
I will add the info to the schematics
