### ISSUE TITLE
panel

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Humpback#3]
@jordens Please have a look at the panel
![obraz](https://user-images.githubusercontent.com/4325054/50936957-14d76b00-1472-11e9-84d1-4007354b0cf7.png)

**Comment by jordens** [comment]
Ok. Nice.
* I guess the screw holes are for mounting the panel insert, right?
* What about removing the panel "bar" at the top (right side when in the crate)? Then a front panel could extend beyond 8 HP and would already be mechanically fixed to Humpback.

**Comment by gkasprow** [comment]
Yes, they are for fixing the panel insert. I can remove the panel bar, but I'm afraid it won't be rigid enough and bend. Why do you want to extend beyond 8HP?

**Comment by jordens** [comment]
To expose e.g. the µC ADC and DAC channels on the front panel. But you are probably right, that's not particular rigid, the use cases for raw ADC and DAC channels are few and if needed one coule hack up a quick 3U raster board, some jumper cables and connectors with its own panel.

**Comment by jordens** [comment]
@gkasprow I think the panel might be covering the edge LEDs on the underside of the board. Add holes?

**Comment by gkasprow** [comment]
Yes, I already added holes.
